/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiGoogleTtsRouteImport } from './routes/api/google-tts'
import { Route as ApiGoogleWorkspaceRouteImport } from './routes/api/google-workspace'
import { Route as ApiMediaSourceRouteImport } from './routes/api/media-source'
import { Route as ApiVideoSourceRouteImport } from './routes/api/video-source'
import { Route as ApiGoogleWorkspaceSplatRouteImport } from './routes/api/google-workspace/$'
import { Route as ApiGoogleWorkspaceCallbackRouteImport } from './routes/api/google-workspace/callback'
import { Route as ApiMusicSplatRouteImport } from './routes/api/music/$'
import { Route as ApiNetworkSplatRouteImport } from './routes/api/network/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleTtsRoute = ApiGoogleTtsRouteImport.update({
  id: '/api/google-tts',
  path: '/api/google-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleWorkspaceRoute = ApiGoogleWorkspaceRouteImport.update({
  id: '/api/google-workspace',
  path: '/api/google-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSourceRoute = ApiMediaSourceRouteImport.update({
  id: '/api/media-source',
  path: '/api/media-source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoSourceRoute = ApiVideoSourceRouteImport.update({
  id: '/api/video-source',
  path: '/api/video-source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleWorkspaceSplatRoute = ApiGoogleWorkspaceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiGoogleWorkspaceRoute,
} as any)
const ApiGoogleWorkspaceCallbackRoute =
  ApiGoogleWorkspaceCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiGoogleWorkspaceRoute,
  } as any)
const ApiMusicSplatRoute = ApiMusicSplatRouteImport.update({
  id: '/api/music/$',
  path: '/api/music/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkSplatRoute = ApiNetworkSplatRouteImport.update({
  id: '/api/network/$',
  path: '/api/network/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/ask': typeof ApiAskRoute
  '/api/google-tts': typeof ApiGoogleTtsRoute
  '/api/google-workspace': typeof ApiGoogleWorkspaceRouteWithChildren
  '/api/media-source': typeof ApiMediaSourceRoute
  '/api/video-source': typeof ApiVideoSourceRoute
  '/api/google-workspace/$': typeof ApiGoogleWorkspaceSplatRoute
  '/api/google-workspace/callback': typeof ApiGoogleWorkspaceCallbackRoute
  '/api/music/$': typeof ApiMusicSplatRoute
  '/api/network/$': typeof ApiNetworkSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/ask': typeof ApiAskRoute
  '/api/google-tts': typeof ApiGoogleTtsRoute
  '/api/google-workspace': typeof ApiGoogleWorkspaceRouteWithChildren
  '/api/media-source': typeof ApiMediaSourceRoute
  '/api/video-source': typeof ApiVideoSourceRoute
  '/api/google-workspace/$': typeof ApiGoogleWorkspaceSplatRoute
  '/api/google-workspace/callback': typeof ApiGoogleWorkspaceCallbackRoute
  '/api/music/$': typeof ApiMusicSplatRoute
  '/api/network/$': typeof ApiNetworkSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/ask': typeof ApiAskRoute
  '/api/google-tts': typeof ApiGoogleTtsRoute
  '/api/google-workspace': typeof ApiGoogleWorkspaceRouteWithChildren
  '/api/media-source': typeof ApiMediaSourceRoute
  '/api/video-source': typeof ApiVideoSourceRoute
  '/api/google-workspace/$': typeof ApiGoogleWorkspaceSplatRoute
  '/api/google-workspace/callback': typeof ApiGoogleWorkspaceCallbackRoute
  '/api/music/$': typeof ApiMusicSplatRoute
  '/api/network/$': typeof ApiNetworkSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/api/ask'
    | '/api/google-tts'
    | '/api/google-workspace'
    | '/api/media-source'
    | '/api/video-source'
    | '/api/google-workspace/$'
    | '/api/google-workspace/callback'
    | '/api/music/$'
    | '/api/network/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/api/ask'
    | '/api/google-tts'
    | '/api/google-workspace'
    | '/api/media-source'
    | '/api/video-source'
    | '/api/google-workspace/$'
    | '/api/google-workspace/callback'
    | '/api/music/$'
    | '/api/network/$'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/api/ask'
    | '/api/google-tts'
    | '/api/google-workspace'
    | '/api/media-source'
    | '/api/video-source'
    | '/api/google-workspace/$'
    | '/api/google-workspace/callback'
    | '/api/music/$'
    | '/api/network/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiGoogleTtsRoute: typeof ApiGoogleTtsRoute
  ApiGoogleWorkspaceRoute: typeof ApiGoogleWorkspaceRouteWithChildren
  ApiMediaSourceRoute: typeof ApiMediaSourceRoute
  ApiVideoSourceRoute: typeof ApiVideoSourceRoute
  ApiMusicSplatRoute: typeof ApiMusicSplatRoute
  ApiNetworkSplatRoute: typeof ApiNetworkSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-tts': {
      id: '/api/google-tts'
      path: '/api/google-tts'
      fullPath: '/api/google-tts'
      preLoaderRoute: typeof ApiGoogleTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-workspace': {
      id: '/api/google-workspace'
      path: '/api/google-workspace'
      fullPath: '/api/google-workspace'
      preLoaderRoute: typeof ApiGoogleWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-source': {
      id: '/api/media-source'
      path: '/api/media-source'
      fullPath: '/api/media-source'
      preLoaderRoute: typeof ApiMediaSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-source': {
      id: '/api/video-source'
      path: '/api/video-source'
      fullPath: '/api/video-source'
      preLoaderRoute: typeof ApiVideoSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-workspace/$': {
      id: '/api/google-workspace/$'
      path: '/$'
      fullPath: '/api/google-workspace/$'
      preLoaderRoute: typeof ApiGoogleWorkspaceSplatRouteImport
      parentRoute: typeof ApiGoogleWorkspaceRoute
    }
    '/api/google-workspace/callback': {
      id: '/api/google-workspace/callback'
      path: '/callback'
      fullPath: '/api/google-workspace/callback'
      preLoaderRoute: typeof ApiGoogleWorkspaceCallbackRouteImport
      parentRoute: typeof ApiGoogleWorkspaceRoute
    }
    '/api/music/$': {
      id: '/api/music/$'
      path: '/api/music/$'
      fullPath: '/api/music/$'
      preLoaderRoute: typeof ApiMusicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network/$': {
      id: '/api/network/$'
      path: '/api/network/$'
      fullPath: '/api/network/$'
      preLoaderRoute: typeof ApiNetworkSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiGoogleWorkspaceRouteChildren {
  ApiGoogleWorkspaceSplatRoute: typeof ApiGoogleWorkspaceSplatRoute
  ApiGoogleWorkspaceCallbackRoute: typeof ApiGoogleWorkspaceCallbackRoute
}

const ApiGoogleWorkspaceRouteChildren: ApiGoogleWorkspaceRouteChildren = {
  ApiGoogleWorkspaceSplatRoute: ApiGoogleWorkspaceSplatRoute,
  ApiGoogleWorkspaceCallbackRoute: ApiGoogleWorkspaceCallbackRoute,
}

const ApiGoogleWorkspaceRouteWithChildren =
  ApiGoogleWorkspaceRoute._addFileChildren(ApiGoogleWorkspaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  ApiAskRoute: ApiAskRoute,
  ApiGoogleTtsRoute: ApiGoogleTtsRoute,
  ApiGoogleWorkspaceRoute: ApiGoogleWorkspaceRouteWithChildren,
  ApiMediaSourceRoute: ApiMediaSourceRoute,
  ApiVideoSourceRoute: ApiVideoSourceRoute,
  ApiMusicSplatRoute: ApiMusicSplatRoute,
  ApiNetworkSplatRoute: ApiNetworkSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
