/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiGoogleTtsRouteImport } from './routes/api/google-tts'
import { Route as ApiMediaSourceRouteImport } from './routes/api/media-source'
import { Route as ApiVideoSourceRouteImport } from './routes/api/video-source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleTtsRoute = ApiGoogleTtsRouteImport.update({
  id: '/api/google-tts',
  path: '/api/google-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSourceRoute = ApiMediaSourceRouteImport.update({
  id: '/api/media-source',
  path: '/api/media-source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoSourceRoute = ApiVideoSourceRouteImport.update({
  id: '/api/video-source',
  path: '/api/video-source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ask': typeof ApiAskRoute
  '/api/google-tts': typeof ApiGoogleTtsRoute
  '/api/media-source': typeof ApiMediaSourceRoute
  '/api/video-source': typeof ApiVideoSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ask': typeof ApiAskRoute
  '/api/google-tts': typeof ApiGoogleTtsRoute
  '/api/media-source': typeof ApiMediaSourceRoute
  '/api/video-source': typeof ApiVideoSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ask': typeof ApiAskRoute
  '/api/google-tts': typeof ApiGoogleTtsRoute
  '/api/media-source': typeof ApiMediaSourceRoute
  '/api/video-source': typeof ApiVideoSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/ask'
    | '/api/google-tts'
    | '/api/media-source'
    | '/api/video-source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/ask'
    | '/api/google-tts'
    | '/api/media-source'
    | '/api/video-source'
  id:
    | '__root__'
    | '/'
    | '/api/ask'
    | '/api/google-tts'
    | '/api/media-source'
    | '/api/video-source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiGoogleTtsRoute: typeof ApiGoogleTtsRoute
  ApiMediaSourceRoute: typeof ApiMediaSourceRoute
  ApiVideoSourceRoute: typeof ApiVideoSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-tts': {
      id: '/api/google-tts'
      path: '/api/google-tts'
      fullPath: '/api/google-tts'
      preLoaderRoute: typeof ApiGoogleTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-source': {
      id: '/api/media-source'
      path: '/api/media-source'
      fullPath: '/api/media-source'
      preLoaderRoute: typeof ApiMediaSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-source': {
      id: '/api/video-source'
      path: '/api/video-source'
      fullPath: '/api/video-source'
      preLoaderRoute: typeof ApiVideoSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAskRoute: ApiAskRoute,
  ApiGoogleTtsRoute: ApiGoogleTtsRoute,
  ApiMediaSourceRoute: ApiMediaSourceRoute,
  ApiVideoSourceRoute: ApiVideoSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
